In [5]:
import numpy as np

In [1]:
from agent import ConvNet
from env import ThreeByThreeGameEnv
import torch

In [2]:
env = ThreeByThreeGameEnv()


In [3]:
obs, _ = env.reset()

In [12]:
hidden_dim = 128
net1 = ConvNet(hidden_dim, kernal_size=(1,3))
net2 = ConvNet(hidden_dim, kernal_size=(3,1))
out1 = net1(torch.from_numpy(obs[np.newaxis,:,:]).to(dtype=torch.float))
out2 = net2(torch.from_numpy(obs[np.newaxis,:,:]).to(dtype=torch.float))
print(out1)
print(out2)

tensor([[[-1.0006e+01],
         [-4.0917e+00],
         [-0.0000e+00]],

        [[-2.8394e+00],
         [-7.5013e+00],
         [-1.0092e+01]],

        [[-3.0589e+01],
         [-1.7478e+01],
         [-2.3563e+01]],

        [[ 7.2695e+01],
         [ 1.5682e+01],
         [ 3.7585e+01]],

        [[-0.0000e+00],
         [-9.2532e+00],
         [-1.1108e+01]],

        [[-0.0000e+00],
         [-1.1997e+01],
         [-9.3677e+00]],

        [[ 1.2584e+02],
         [ 8.4892e+01],
         [ 1.0188e+02]],

        [[ 3.2519e+01],
         [ 6.1693e+01],
         [ 3.6966e+01]],

        [[ 7.8468e+00],
         [ 5.6115e+01],
         [ 9.1899e+00]],

        [[-3.0569e+00],
         [-5.2427e-01],
         [ 1.3210e+00]],

        [[ 8.3214e+01],
         [ 9.2237e+01],
         [ 7.8505e+01]],

        [[-1.6489e+01],
         [-8.3306e+00],
         [-1.6355e+01]],

        [[ 4.5403e+01],
         [ 2.3333e+01],
         [ 1.6797e+01]],

        [[ 9.2114e+01],
         [ 3.8

In [13]:
out2 = torch.swapaxes(out2, 1,2)

In [14]:
torch.cat([out1, out2], dim=1)

tensor([[[-1.0006e+01],
         [-4.0917e+00],
         [-0.0000e+00],
         [-6.9439e+00],
         [ 4.0306e+01],
         [-8.4139e-01]],

        [[-2.8394e+00],
         [-7.5013e+00],
         [-1.0092e+01],
         [ 5.8917e+01],
         [ 3.8644e+01],
         [ 6.1792e+01]],

        [[-3.0589e+01],
         [-1.7478e+01],
         [-2.3563e+01],
         [-7.9021e+00],
         [ 4.0422e+01],
         [-3.0713e-01]],

        [[ 7.2695e+01],
         [ 1.5682e+01],
         [ 3.7585e+01],
         [-0.0000e+00],
         [-1.4283e+01],
         [-7.9674e+00]],

        [[-0.0000e+00],
         [-9.2532e+00],
         [-1.1108e+01],
         [-1.0111e+01],
         [-2.2264e+01],
         [-1.6705e+01]],

        [[-0.0000e+00],
         [-1.1997e+01],
         [-9.3677e+00],
         [-1.0936e+00],
         [ 3.7973e+01],
         [ 1.9609e+01]],

        [[ 1.2584e+02],
         [ 8.4892e+01],
         [ 1.0188e+02],
         [-1.6851e-01],
         [-7.1216e+00],
    

In [32]:
a.diagonal()

array([18,  5, 15])

In [31]:
np.fliplr(a).diagonal()

array([12,  5,  9])

In [40]:
(~a.any(axis=0)).any()

True

In [8]:
list(range(0,9,2)), list(range(1,10,2)) 
to_play = 0
# to_play = 1
l = 10
b = list(range(to_play , l - 1 + to_play, 2))


In [9]:
a = list(range(100, 200))
a[b]

TypeError: list indices must be integers or slices, not list

In [10]:
a = [("Jonny", (1,3)),("Jonny", (1,3)),("Jonny", (1,3))]

In [20]:
c,d = map(list, zip(*a))
c

['Jonny', 'Jonny', 'Jonny']

In [61]:
a

array([[ 8,  0,  6],
       [ 3,  9,  0],
       [ 0, 15, 19]])