In [1]:
import numpy as np

In [51]:
a = np.random.randint(1,20,(3,3))

In [52]:
a

array([[12, 18,  2],
       [ 3, 14,  7],
       [ 8, 10,  5]])

In [4]:
a[1,:]

array([1, 3, 1])

In [6]:
a[:,1].min()

3

In [7]:
list(range(1,4))

[1, 2, 3]

In [23]:
b = np.s_[:,1]
a[b]

array([4, 3, 6])

In [32]:
a.diagonal()

array([18,  5, 15])

In [31]:
np.fliplr(a).diagonal()

array([12,  5,  9])

In [40]:
(~a.any(axis=0)).any()

True

In [39]:
a[:, 1] = 0
a

array([[18,  0, 12],
       [ 0,  0,  0],
       [ 9,  0, 15]])

In [53]:
a

array([[12, 18,  2],
       [ 3, 14,  7],
       [ 8, 10,  5]])

In [56]:
(a == 0).any(axis=0).all()

False

In [60]:
a = np.random.randint(1,20,(3,3))
a[0,1] = 0
a[1,2] = 0
a[2, 0] = 0
(a == 0).any(axis=0).all()

True

In [61]:
a

array([[ 8,  0,  6],
       [ 3,  9,  0],
       [ 0, 15, 19]])